# Generated by Django 4.2.7 on 2023-11-12 18:28

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_artwork_artist_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artwork",
            name="preview_image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                null=True,
                quality=80,
                scale=None,
                size=[800, None],
                upload_to="preview_images/",
            ),
        ),
    ]
