# Generated by Django 4.2.7 on 2023-11-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="artist_name",
            field=models.CharField(default="Unknown", max_length=30),
        ),
    ]
